<!DOCTYPE html>
<html>
<head>
	<title>Manifest Report</title>
	<style>
		.main {
			width: 100%;
		}
		.container {
			max-width: 600px;
			width: 100%;
			margin: 0 auto;
		}
		.topback {
			background: #CCC;
			float: left;
		}
		.forcenter {
			text-align: center;
		}
		.sizeheading {
			font-size: 26px;
			border:1px solid #000;
			border-bottom:none;
		}
		.sizeheadingnew {
			font-size: 12px;
		}
		.sizeheadingnew2 {
			font-size: 14px;
		}
		.contentsize {
			font-size: 18px;
		}
		.colorheidding {
			color: #000;
			font-weight:600;
		}
		.forbold {
			font-weight: 900;
		}
		.fontweight {
			font-weight: bolder;
		}
		.toppading {
			padding-top: 20px;
		}
		.forleft {
			text-align: left;
		}
		.forright {
			text-align: right;
		}
		.bothsidepadding tr {
			padding-let: 10px;
			padding-right: 10px;
		}
		.paddingleft {
			padding-left: 10px;
		}
		.paddingright {
			padding-right: 32px;
		}
		.paddboth {
			padding-left: 10px;
			padding-right: 10px;
		}
		.floatrt {
			float: right;
		}
		.borderbottom {
			border-bottom: solid 1px;
		}
		.borderright {
			border-right: 2px solid;
		}
		.borderblack {
			border: solid 1px #000;
		}
		.main1 {
			width: 30%;
			float: left;
		}
		.main2 {
			width: 90%;
			float: right;
		}
		.tbborder {
			border: solid 1px;
		}
		.bordeb1 {
			border-bottom: 1px solid;
		}
		.rightlectricbord {
			border-right: solid 1px;
		}
		.borboth1 {
			border: 1px solid #000;
		}
		.borboth {
			border-right: 1px solid #000;
			border-bottom: 1px solid #000;
		}
		.blackbotomborer {
			border-bottom: 1px solid #000;
		}
		.rightblack {
			border-right: 1px solid #000;
		}
		.topblack {
			border-top: solid 1px #000;
		}
		.lefttopbottom {
			border-left: solid 1px #000;
			border-top: solid 1px #000;
			border-bottom: 1px solid #000;
		}
		.leftrighttop {
			border-left: solid 1px #000;
			border-right: 1px solid #000;
			border-top: solid 1px #000;
		}
		.rightleftbottom {
			border-left: solid 1px #000;
			border-right: 1px solid #000;
			border-bottom: 1px solid #000;
		}
		.one {
			width: 50%;
			float: left;
			text-align: left;
		}
		.one1 {
			width: 50%;
			float: right;
			text-align: left;
		}
		.space {
			margin-left: 5px;
		}
		.margintopnote {
			margin-top: 15px;
		}
		.margin-bottom {
			margin-bottom: 30px;
		}
		.leftright {
			border-left: solid 1px #000;
			border-right: 1px solid #000;
		}
		.borboth:nth-child(6),.rightblack:nth-child(6){
			border-right:none;
		}
		.mb-20{
			border:1px solid;
			border-bottom:none;
			padding:10px;
		}
	</style>

</head>
<body>
<?php 
     //dd($manifest)
     ?>
	<div class="container">
		<div class="main">
			<table cellspacing="0" class="main   forleft bothsidepadding" height="60">
				<tbody>
					<tr>
						<th style="text-align: center;font-family: 'Raleway', sans-serif;" class="main forcenter forbold sizeheading ">Techturtle.in</th>
					</tr>
				</tbody>
			</table>

			<table class="main forleft bothsidepadding mb-20">
				<tbody><tr>
					<td class="sizeheadingnew2">Manifest Id:</td>
					<td>{{ $manifest->id + 987654321}}</td>
				</tr>
				
				<tr>
					<td class="sizeheadingnew2"></td>

					<td><img src="{{ url('order/barcode/'.$manifest->awb)}}"></td>
				</tr>
				<tr>
					<td class="sizeheadingnew2 ">Carrier Name:</td>

					<td> </td>
				</tr>
				<tr>
					<td class="sizeheadingnew2">Dispatch Date: </td>
					<td>{{ $manifest->dispatchDate}}</td>
				</tr>
				<tr>
					<td class="sizeheadingnew2 ">No of Shipments:</td>
					<td>1</td>
				</tr>
				<tr>
					<td class="sizeheadingnew2 ">Pick Up Boy:</td>
				</tr>
				<tr>
					<td class="sizeheadingnew2 ">Pick Up Vehicle No:</td>
				</tr>
				<tr>
					<td class="sizeheadingnew2 ">Pick Up Location:</td>
				</tr>
				<tr>
					<td class="sizeheadingnew2 ">Report Generated By:</td>
					<td>{{$manifest->reportGeneratedBy}}</td>
				</tr>
				<tr>
					<td class="sizeheadingnew2 ">Manifest Type:</td>

					<td>Courier Manifest</td>
				</tr>
				<tr>
					<td class="sizeheadingnew2 ">Notes:</td>
				</tr>
			</tbody></table>

			<table width="100%" cellspacing="0" cellpadding="2" class=" tbborder">
				<tbody><tr>
					<td width="7%" class="sizeheadingnew colorheidding forcenter borboth">S. No</td>
					<td class="sizeheadingnew colorheidding forcenter borboth">Order Id</td>
					<td class="sizeheadingnew colorheidding forcenter borboth">Buyer Detail</td>
					<td class="sizeheadingnew colorheidding forcenter borboth">Colectible Amount</td>
					<td class="sizeheadingnew colorheidding forcenter borboth">Payment Mode</td>
				</tr>
				<tr>
					<td class="sizeheadingnew  forcenter rightblack">1</td>
					<td class="sizeheadingnew  forcenter rightblack">{{$orders->id}}</td>
					<td class="sizeheadingnew  forcenter rightblack">{{ucwords(strtolower($orders->customerName))}}<br>
						{!! $orders->shippingCompleteAddress() !!}</td>
						<td class="sizeheadingnew forcenter rightblack"><i class="fa fa-inr"></i> {{$orders->orderAmount}}</td>
						<td class="sizeheadingnew forcenter rightblack">{{$orders->paymentType}}</td>
					</tr>
				</tbody>				
				</table>
				<table width="100%" cellspacing="0" cellpadding="2" class=" tbborder">
				<tbody>
				<tr><td class="sizeheadingnew colorheidding forcenter borboth" colspan="7">Product Details</td></tr>
					<tr>
					<td class="sizeheadingnew colorheidding forcenter borboth">SN</td>
						<td class="sizeheadingnew colorheidding forcenter borboth">Product Name</td>
						<td class="sizeheadingnew colorheidding forcenter borboth">Price</td>
						<td class="sizeheadingnew colorheidding forcenter borboth">Varients</td>
					</tr>
					<?php $sn = 1 ?>
					@foreach($orders->products as $product)	
								
					<tr><td class="sizeheadingnew  forcenter rightblack">{{ $sn++}} </td>
						<td class="sizeheadingnew  forcenter rightblack">{!! ucwords(strtolower($product->product_name)) !!}</td>
						<td class="sizeheadingnew  forcenter rightblack">{{$product->selling_price}}</td>
						<td class="sizeheadingnew  forcenter rightblack">{!! $orders->getVarientByIds($product->varients) !!}</td>
					</tr>
					@endforeach
				</tbody>
				</table>
				</div>
		</div>
	</body>
	</html>