<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/bootstrap4/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/themify-icons/themify-icons.css')}}">
<!--<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/font-awesome/css/font-awesome.min.css')}}">-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/animate.css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/jscrollpane/jquery.jscrollpane.css')}}">
<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/waves/waves.min.css')}}">
<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/switchery/dist/switchery.min.css')}}">
<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/morris/morris.css')}}">
<link rel="stylesheet" href="{{asset(ADMIN_FILE_PATH.'/vendor/jvectormap/jquery-jvectormap-2.0.3.css')}}">